version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./cars.db:/app/cars.db
    environment:
      - SQLITE_DATABASE=cars.db
